language: groovy
sudo: false
jdk:
- openjdk7
before_script:
- rm -rf target
script: ./travis-build.sh
env:
  global:
  - GIT_NAME="Graeme Rocher"
  - GIT_EMAIL="graeme.rocher@gmail.com"
  - secure: l26u6hsD6eJ/IkoqATBtJCHZPbcSDwxazID/vE26zJ6upNm+pNfi+AVhmiK39LWTayncYD3jjU2lO1VUyGocxTmvsJq3IIJ5NWQOoNx2NE6Q92/6Y0J+qhYcmt8Puk5rIABH60RdQt4A0Zo+Xd9WkpSau/zpshgNWzPgwBm0aZg=
  - secure: aLHAC0txu6lBq2VPJIlXfw4GyShXysdr5CrH83WJbpEmXH5QOEyECXu5+pPLgbYAF+zeP2ewdNlg/FEHNO/RnhcDVjvuNoTnQ+ap4dwRNMb1/sCYo9IcNw6Hx8lMHykzpwyZ26gaovEzGWdxxql8D0B2WKfzdVs+sZ3qEqJRDKg=
  - secure: fAs++a4rj8BvJ9rWuVF74+T58NeAcnyJa3glCbeLUA+VgY4qGQ9dLBICv9inB7M6i17CeCtUCcykkOZClTCOSgBdCQL2htChJ/9L2U7NjIpIZi/a+pqCO8GAB3/lOdS5TsKvJOuJ7cs6d9pJDVGwwlcRakixT8Ah8BeEfethL1k=
  - secure: dIv+ioRrpswVduGgvmzcuw0BV8oyJnjaJg9LH9AZTJCAbSXvac0ahGFU9BQ6kqPDE0zViSpTvaETOQkPGb12pao/y18EuhLj20WsuPzmRru/eftTFm0Bk9ar8sS9QJ0V/xH6ToUMgjV3ePAjV6yXmaIRoqmjAfjnqrmaClQFsAE=
  - secure: oPPt1cqhE9CdQUegMpWgPMPMdDZd198Ysdr8dELiFJ0tn93/E4ObPEr5+fBPxHre09oyCEm16GRaUUWvkA92vMzVDWe/PhQTEyS6oNS20smqJrQBskvsEzxs/gS/7EsMj3Gc8l9DIrn4BmUCu6pgzbuNx86GySOcUKxi7tz25h8=
  - secure: DkBwxLAnh41ctEgFHTrgsQGFiAayL2MuBCfKRYIVLvnIchbt1JYeU9ofWoblWPurIctzbNJkW03xSX+4XzVvildBWDU3NHIQ7wGklAcU6nj/4jaH0oTkXoUJFiFJWEDcvN4LD7WRHrMS7gR6micVF4DgDgc+Dn+yRi1Isv7+xFA=